name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout --detach FETCH_HEAD
      - name: Prepare Pages Artifact
        run: |
          mkdir page-artifact
          git fetch --depth=1 origin gh-pages
          git archive --format=tar FETCH_HEAD | tar -x -C page-artifact
      - uses: actions/upload-pages-artifact@v4
        with:
          path: page-artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
